"""Turn your real product catalog into grounded training gold for sales/support
lanes, so the model KNOWS every SKU: what it is, what it's for, where it's used,
and what it's compatible with.

Facts come ONLY from the catalog entry (catalog.py) — answers are TEMPLATED from
real fields, never free-generated by an LLM, so the gold itself can't hallucinate
a spec. Question phrasings (DE+EN) and answer templates are rotated per SKU so the
set stays varied (passes the distinctness gate). Pair the resulting trained
knowledge with the answer-time catalog grounding (#4) for the full picture:
expert reasoning (trained) + exact current SKU/price (retrieved).
"""
from __future__ import annotations

import json
from typing import Callable

from . import catalog as _catalog
from .pool import Pool

# Sales/support lanes that should know the whole catalog. Empty by default --
# list the adapter names you want catalog-grounded (or tag them "catalog" and
# filter on that instead, same pattern as the "research" tag in pipeline.py).
CATALOG_LANES: tuple[str, ...] = ()


def _g(entry: dict, key: str, default: str = "") -> str:
    specs = entry.get("specs") or {}
    return str(specs.get(key, entry.get(key.lower(), default)) or default).strip()


def _application(entry: dict) -> tuple[str, str]:
    """Derive (DE, EN) use-case from fiber + reach + form factor — what it's FOR."""
    fiber = (entry.get("fiber") or "").lower()
    reach = entry.get("reach_km") or 0
    ff = _g(entry, "Form Factor") or ""
    bw = _g(entry, "Bandwidth") or ""
    high = any(s in (ff + bw).upper() for s in ("QSFP", "100", "200", "400", "800"))
    if "multimode" in fiber:
        de = "kurze Inhouse-/Rechenzentrums-Strecken (Multimode), Server-zu-Switch und Spine-Leaf"
        en = "short in-house / data-center links (multimode), server-to-switch and spine-leaf"
    elif reach and reach >= 40:
        de = f"Metro-/Long-Haul-Strecken bis ~{int(reach)} km über Singlemode (Aggregation, DCI, Provider-Backbone)"
        en = f"metro / long-haul links up to ~{int(reach)} km over singlemode (aggregation, DCI, provider backbone)"
    elif reach:
        de = f"Campus- und Aggregations-Strecken bis ~{int(reach)} km über Singlemode"
        en = f"campus and aggregation links up to ~{int(reach)} km over singlemode"
    else:
        de = "Direktverbindungen kurzer Reichweite (Top-of-Rack)"
        en = "short-reach direct links (top-of-rack)"
    if high:
        de += " sowie Hochgeschwindigkeits-Uplinks im Core/DC"
        en += " plus high-speed core/DC uplinks"
    return de, en


def _pairs_for(entry: dict) -> list[tuple[str, str]]:
    sku = entry.get("sku", "")
    ff = _g(entry, "Form Factor")
    bw = _g(entry, "Bandwidth")
    dist = _g(entry, "Distance") or (f"{int(entry['reach_km'])} km" if entry.get("reach_km") else "")
    fiber = entry.get("fiber") or _g(entry, "Interface")
    conn = entry.get("connector") or _g(entry, "Connector / Polish")
    temp = _g(entry, "Operating Temperature")
    power = _g(entry, "Power Consumption")
    ddm = _g(entry, "Digital Diagnostic Monitoring (DDM)")
    app_de, app_en = _application(entry)
    h = sum(ord(c) for c in sku)   # deterministic phrasing rotation per SKU

    spec_de = (f"Der {sku} ist ein {ff}-Transceiver ({fiber}, {bw}) für bis zu {dist}, "
               f"{conn}-Anschluss, {temp}-Temperaturbereich"
               + (f", {power} Verbrauch" if power else "")
               + (f", DDM: {ddm}" if ddm else "") + ". vendor-codierbar auf nahezu jeden Switch-Hersteller.")
    spec_en = (f"The {sku} is a {ff} transceiver ({fiber}, {bw}) for up to {dist}, "
               f"{conn} connector, {temp} temperature range"
               + (f", {power} power" if power else "")
               + (f", DDM: {ddm}" if ddm else "") + ". Vendor-codeable to almost any switch brand.")

    q_what_de = ["Was ist der {s}?", "Erklär mir den {s}.", "Was kann der {s}?"][h % 3]
    q_what_en = ["What is the {s}?", "Tell me about the {s}.", "What does the {s} do?"][h % 3]
    q_use_de = ["Wofür setzt man den {s} ein?", "Wo wird der {s} verwendet?",
                "Für welche Strecken eignet sich der {s}?"][h % 3]
    q_use_en = ["What is the {s} used for?", "Where would I deploy the {s}?",
                "Which links is the {s} suited for?"][h % 3]

    pairs = [
        (q_what_de.format(s=sku), spec_de),
        (q_what_en.format(s=sku), spec_en),
        (q_use_de.format(s=sku),
         f"Der {sku} ({ff}, {fiber}, bis {dist}) eignet sich für {app_de}."),
        (q_use_en.format(s=sku),
         f"The {sku} ({ff}, {fiber}, up to {dist}) suits {app_en}."),
        (f"Passt der {sku} an einen Cisco/Juniper/Arista-Switch?",
         f"Ja — der {sku} ist vendor-codierbar auf nahezu jeden Switch-Hersteller (Cisco, Juniper, Arista, "
         f"Nokia, Huawei u.v.m.). Sag mir das genaue Switch-Modell, dann bestätige ich die Codierung."),
    ]
    return [(u, a) for u, a in pairs if u and a and sku in a]


def generate(settings, lanes: tuple[str, ...] = CATALOG_LANES, *,
             write: bool = True, log: Callable[[str], None] = print) -> dict:
    """Build grounded catalog-knowledge gold and append it to each configured lane's pool."""
    cat = _catalog._catalog()
    if not cat:
        return {"ok": False, "reason": "catalog snapshot not available"}
    examples = []
    for entry in cat.values():
        for user, answer in _pairs_for(entry):
            examples.append({
                "messages": [{"role": "user", "content": user},
                             {"role": "assistant", "content": answer}],
                "_meta": {"source": "catalog", "verified": True, "origin": "catalog",
                          "quality_score": 92, "sku": entry.get("sku")},
            })
    out: dict = {"ok": True, "generated": len(examples), "lanes": {}}
    if write:
        for lane in lanes:
            res = Pool(settings.pool_path, lane).append(examples, split="gold")
            out["lanes"][lane] = res
            log(f"catalog-gen: {lane} += {res['added']} gold ({res['skipped']} dupes)")
    return out
